### ISSUE TITLE
Trying to use any value in a Varbind results in an exception being thrown when attempting to set

### ISSUE THREAD

**Issue by repnop** [bluecmd/python3-netsnmp#6]
Reproduction:
```python
>>> import netsnmp
>>> session = netsnmp.Session(Version = 2, DestHost='localhost', Community='public')
>>> vbind = netsnmp.Varbind('sysUpTime', 0, 1, 'INTEGER')
>>> session.set(netsnmp.VarList(vbind))
TypeError: expected bytes, int found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.6/site-packages/netsnmp/client.py", line 205, in set
    res = client_intf.set(self, varlist)
SystemError: <built-in function set> returned a result with an error set
```

Even when using a `bytes` object, it throws a different exception.

Issue seems to be from this call here:
https://github.com/bluecmd/python3-netsnmp/blob/9f51ee26b3f70ddca9f35116ae53a08c16bb6b8f/netsnmp/client_intf.c#L1047
As per the Python 3 documentation [here](https://docs.python.org/3.8/c-api/bytes.html#c.PyBytes_AsStringAndSize):
>  If obj is not a bytes object at all, PyBytes_AsStringAndSize() returns -1 and raises TypeError.

This makes the library completely unusable if you ever need to try and set a value

**Comment by voidtrance** [comment]
I am seeing the same issue with `Session.get()`:

```.py
>>> session = snmp.Session(DestHost=hostname, Version=3, UseNumeric=True,
...                                SecName=username, SecLevel="authPriv",
...                                AuthProto="SHA", PrivProto="DES",
...                                AuthPass=auth_passwd, PrivPass=priv_passwd)
>>> v = snmp.VarList(snmp.Varbind(".1.3.6.1.4.1.318.1.1.12.3.1.3", ".0"))
>>> session.get(v)
TypeError: expected bytes, str found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.7/site-packages/netsnmp/client.py", line 196, in get
    res = netsnmp.client_intf.get(self, varlist)
SystemError: <built-in function get> returned a result with an error set
```
I've even tried constructing the `Varbind` instances like this:
```.py
snmp.VarList(snmp.Varbind(b".1.3.6.1.4.1.318.1.1.12.3.1.3", b".0"))
```
and
```.py
snmp.VarList(snmp.Varbind(b".1.3.6.1.4.1.318.1.1.12.3.1.3", b".0", None, b'INTEGER'))
```
None of the above work, resulting in the same error.

Interestingly enough, `Session.getnext()` works:
```.py
>>> v = snmp.VarList(snmp.Varbind(".1.3.6.1.4.1.318.1.1.12.3.1.3", ".0"))
>>> session.getnext(v)
('8',)
```
Between a broken `Session.get()` and `Session.set()`, the entire module is pretty unusable. This issue has not had any attention since it was opened, which is surprising given that both `set` and `get` are broken.

**Comment by shameersirajuddin** [comment]
@repnop - I'm stuck with the exact same problem. Can you point me to what ended up working for you?

**Comment by repnop** [comment]
@shameersirajuddin oh jeez, its been a _long_ time since I last dealt with this. I want to say I may have ended up modifying the source to get it to work -- I'll try and find out at some point but feel free to ping me after a while if I don't respond
